### ISSUE TITLE
Lab 1 Deliverable 1

### ISSUE THREAD

**Issue by rwaters2** [LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-rwaters2#1]
See screenshot for pulling down git repo and running git log
<img width="712" alt="Screenshot 2024-11-02 at 3 36 37 PM" src="https://github.com/user-attachments/assets/c6955e16-7438-4a47-8728-b7ae5d9b0fc3">

**Comment by instructorc** [comment]
Nice Work!  Requirement met!
